server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    # Настройки балансировщика
    loadbalancer:
      ribbon:
        enabled: false # Отключаем старый Ribbon в пользу нового LoadBalancer
      cache:
        enabled: false # Отключаем кэш для теста, чтобы видеть переключение между инстансами сразу
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # ---- доставка ----
        - id: delivery_service_route
          uri: lb://delivery
          predicates:
            - Path=/delivery/**
          filters:
            - PrefixPath=/api/v1

        # ---- оплата ----
        - id: payment_service_route
          uri: lb://payment
          predicates:
            - Path=/payment/**
          filters:
            - PrefixPath=/api/v1

        # ---- заказы ----
        - id: order_service_route
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - PrefixPath=/api/v1

        # ---- корзина ----
        - id: shopping_cart_service_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
          filters:
            - PrefixPath=/api/v1
        # ---- склад ----
        - id: warehouse_service_route
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**
          filters:
            - PrefixPath=/api/v1
            - name: CircuitBreaker
              args:
                name: warehouseCircuitBreaker
        # ---- магазин ----
        - id: shopping_store_service_route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
          filters:
            - PrefixPath=/api/v1

resilience4j:
  circuitbreaker:
    instances:
      warehouseCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

# ---- Настройки логирования ----
logging:
  level:
    root: INFO

      # Логи входящих HTTP-запросов в Gateway (от клиента к Gateway).
    reactor.netty.http.server: DEBUG

      # Логи исходящих HTTP-запросов из Gateway (от Gateway к микросервису).
    reactor.netty.http.client: DEBUG

#   --------------------------------------------------памятка----------------------------
#  1.  prefer-ip-address: true — Всегда используйте это в локальной разработке (особенно на Windows), чтобы сервисы находили друг друга по IP, а не по капризным именам хостов типа Skynet.mshome.net.
#  2.  instance-id — Чтобы запускать несколько копий одного сервиса на одной машине, ID должен быть уникальным (через ${random.value} или ${server.port}).
#  3.  lb://service-name — В шлюзе это включает балансировку. Чтобы она работала «честно» и без ошибок WARN, важно отключать старый ribbon и использовать spring-cloud-starter-loadbalancer.
#  4.  Path=/* — В предикатах шлюза всегда ставьте двойную звездочку, если хотите, чтобы маршрут ловил все вложенные эндпоинты (например, /address, /check, /add).
