spring:
  application:
    name: warehouse
  sql:
    init:
      mode: always
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:6435/smart-home-commerce-warehouse"
    username: "username"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: create-drop #none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: warehouse
        format_sql: true

eureka:
  instance:
    # Использовать IP вместо имени хоста (решает проблему с DNS)
    prefer-ip-address: true
    # Явно задаем формат ID, чтобы там был IP, а не имя хоста
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${random.value}

server:
  port : 0 #63524




#    show-sql: true  # Добавляем здесь
#    logging: # Добавляем секцию логирования
#      level:
#        org:
#          hibernate:
#            SQL: DEBUG
#            type:
#              descriptor:
#                sql:
#                  BasicBinder: TRACE