spring:
  application:
    name: warehouse
  sql:
    init:
      mode: always
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:6435/smart-home-commerce-warehouse"
    username: "username"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: create-drop #none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: warehouse
        format_sql: true

#    show-sql: true  # Добавляем здесь
#    logging: # Добавляем секцию логирования
#      level:
#        org:
#          hibernate:
#            SQL: DEBUG
#            type:
#              descriptor:
#                sql:
#                  BasicBinder: TRACE

server:
  port : 0 #63524

