spring:
  application:
    name: warehouse
  sql:
    init:
      mode: always
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:6435/smart-home-commerce-warehouse"
    username: "username"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: create-drop #none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: warehouse
        format_sql: true

server:
  port : 0 #12345 #59944 #0

