application:
  name: aggregator

kafka:
  kafka-servers: localhost:9092
  topic-sensors: telemetry.sensors.v1
  topic-snapshots: telemetry.snapshots.v1
  group-id: telemetry.aggregator
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: ru.yandex.practicum.deserializer.SensorEventDeserializer
  value-serializer: ru.yandex.practicum.serializer.GeneralAvroSerializer
  consumer:
    enable-auto-commit: false
    poll-timeout: 100
server:
  port : 8082

