spring:
  application:
    name: aggregator

  config:
  # import: configserver:http://localhost:8888 Указывает на расположение Config Server, если напрямую
    import: "configserver:"  # используем Service Discovery

  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

# Настройки Eureka клиента
eureka:
  client:
    serviceUrl:  # URL для связи с Eureka сервером
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
      # Используются переменные для гибкости настройки хоста и порта
      # По умолчанию используется localhost:8761