kafka:
  topics:
    snapshots: "telemetry.snapshots.v1"
    hubs: "telemetry.hubs.v1"
  hub-consumer-properties:
    group-id: analyzer-hub-group
  snapshot-consumer-properties:
    group-id: analyzer-snapshot-group
  bootstrap-servers: localhost:9092


grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext


spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/analyzer"
    username: "postgres"
    password: "12345"
  sql:
    init:
      data-locations: classpath:schema.sql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          time_zone: UTC